# Generated by Django 3.0.4 on 2021-02-11 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('publicada', models.DateTimeField(default=django.utils.timezone.now)),
                ('criada', models.DateTimeField(auto_now_add=True)),
                ('atualizada', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('publicada', 'Publicada'), ('rascunho', 'Rascunho')], default='rascunho', max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
